// <auto-generated />
using System;
using Deborah.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DeborahCall.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Deborah.Models.Mst_Communication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Com_Name");

                    b.HasKey("Id");

                    b.ToTable("Mst_Communication");
                });

            modelBuilder.Entity("Deborah.Models.Mst_Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Status_Name");

                    b.HasKey("Id");

                    b.ToTable("Mst_Status");
                });

            modelBuilder.Entity("Deborah.Models.Mst_System", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("System_name");

                    b.HasKey("Id");

                    b.ToTable("Mst_System");
                });

            modelBuilder.Entity("Deborah.Models.Mst_Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Type_Name");

                    b.HasKey("Id");

                    b.ToTable("Mst_Type");
                });

            modelBuilder.Entity("Deborah.Models.Mst_User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Hostname");

                    b.Property<string>("Password");

                    b.Property<string>("User_Name");

                    b.HasKey("Id");

                    b.ToTable("Mst_User");
                });

            modelBuilder.Entity("Deborah.Models.Tra_Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("End_Time");

                    b.Property<DateTime>("Entry_Time");

                    b.Property<string>("Hostname");

                    b.Property<string>("Tel_No");

                    b.HasKey("Id");

                    b.ToTable("Tra_Entry");
                });

            modelBuilder.Entity("Deborah.Models.Tra_Inqury", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Answer");

                    b.Property<long>("Cause");

                    b.Property<int>("Com_Id");

                    b.Property<string>("Company_Name");

                    b.Property<int>("Entry_Id");

                    b.Property<bool>("Incomplate_Flag");

                    b.Property<long>("Inqury");

                    b.Property<int>("Relation_Id");

                    b.Property<bool>("Staff_Flag");

                    b.Property<int>("System_Id");

                    b.Property<string>("Tan_Name");

                    b.Property<string>("Tel_No");

                    b.Property<int>("Type_Id");

                    b.HasKey("Id");

                    b.ToTable("Tra_Inqury");
                });
#pragma warning restore 612, 618
        }
    }
}
